name: release

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: CD
        run: cd app

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --prefer-offline, --ignore-scripts]

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: diff
          actions_comment: false
          working_dir: app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: ap-northeast-1
          INFLUX_DB_BUCKET: ${{ secrets.INFLUX_DB_BUCKET_DEV }}
          INFLUX_DB_ORG: ${{ secrets.INFLUX_DB_ORG_DEV }}
          INFLUX_DB_TOKEN: ${{ secrets.INFLUX_DB_TOKEN_DEV }}
          STAGE: dev

      - name: Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: deploy
          cdk_args: '--require-approval never'
          actions_comment: false
          working_dir: app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: ap-northeast-1
          INFLUX_DB_BUCKET: ${{ secrets.INFLUX_DB_BUCKET_DEV }}
          INFLUX_DB_ORG: ${{ secrets.INFLUX_DB_ORG_DEV }}
          INFLUX_DB_TOKEN: ${{ secrets.INFLUX_DB_TOKEN_DEV }}
          STAGE: dev

