name: release

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: [1.16.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: test
        run: deno test -A

  release:
    needs: [test]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: [1.16.0]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=name::${GITHUB_REF#refs/heads/}"
        id: branch

      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ steps.branch.outputs.name }}

      - name: CD
        run: cd app

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
          run_install: true

      - name: cdk diff
        run: |
          pwd
          cd app
          pnpm cdk -c environment=dev diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', steps.string.outputs.uppercase )] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', steps.string.outputs.uppercase )] }}
          AWS_DEFAULT_REGION: ap-northeast-1

      - name: Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: deploy
          cdk_args: ${{ format('--require-approval never -c environment={0}', steps.branch.outputs.name ) }}
          actions_comment: false
          working_dir: app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', steps.string.outputs.uppercase )] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', steps.string.outputs.uppercase )] }}
          AWS_DEFAULT_REGION: ap-northeast-1

